server:
  port: 9000

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway

zuul:
  routes:
#    配置服务映路径，注意路径名不能一样
    order-service: /osgateway/**
    product-service: /psgateway/**
#  忽略并拒绝匹配定义的模式路径访问
#  ignored-patterns: /*-service/**
#  忽略并拒绝直接访问指定的服务
#  ignored-services: order-service
#  处理zuul网关无法获取http请求头信息问题，但是此方法不知为何在此无效
  sensitive-headers:
